language: python

python:
    - "2.6"
    - "2.7"

sudo: false

install:
    - pip install tox

script:
    - tox

env:
    - TOXENV=django14
    - TOXENV=django15
    - TOXENV=django16
    - TOXENV=flake8
